### ISSUE TITLE
Integrate the Microsoft mvvm Toolkit

### ISSUE THREAD

**Issue by SimonGeering** [SimonGeering/AdminAssistant#93]
See <https://github.com/windows-toolkit/WindowsCommunityToolkit/tree/master/Microsoft.Toolkit.Mvvm>

- [ ] Add comment to <https://github.com/windows-toolkit/WindowsCommunityToolkit/issues/3428> re lack of zero param overloads.
- [ ] Submit PR to the community toolkit master branch.

**Comment by Sergio0694** [comment]
Hey @SimonGeering - it's great folks trying out the new MVVM Toolkit, hope it's going well so far! 😄

Just a couple notes:
1) Keep in mind the API surface might change a bit in a couple places when the next preview drops (just a heads up). I'm keeping an updated list of all changes in https://github.com/windows-toolkit/WindowsCommunityToolkit/issues/3428, and you can also browse through the various commits in the two linked PRs if you're interested. That's to say, the `master` branch in the toolkit does not reflect the actual current state of the MVVM Toolkit, as that doesn't account for all the pending changes there.
2) Regarding that "lack of zero param overloads", curious to hear more about that, what your use case scenario is, etc. Please feel free to share feedbacks in the linked issue so we can discuss this (if we do settle on a new API to add, I'll just include it in one of my two tracking PRs, so that we'll have all pending changes for the toolkit in a single place, which makes things easier) 😊

**Comment by SimonGeering** [comment]
Hi @Sergio0694 - very kind of you to take the time and trouble to reach out on here 😃 👍

The Xamarin app is a placeholder project for now but I am actively working on both a Desktop (WPF) and Web (Blazor Webasm) UI with a shared view model using CleanArchitecture. 

The app is very "early days" as it stands with [BankAccountEditDialogViewModel](https://github.com/SimonGeering/AdminAssistant/blob/simon/src/AdminAssistant.UI/Modules/AccountsModule/BankAccountEditDialog/BankAccountEditDialogViewModel.cs) being the only VM anywhere near functional and integrated with the corresponding [BankAccountEditDialog.xaml](https://github.com/SimonGeering/AdminAssistant/blob/simon/src/AdminAssistant.Desktop/WPF/AdminAssistant.WPF/Modules/AccountsModule/BankAccountEditDialog.xaml) WPF dialog and the [BankAccountEditDialogComponent.razor](https://github.com/SimonGeering/AdminAssistant/blob/simon/src/AdminAssistant.Blazor/Client/Modules/AccountsModule/BankAccountEditDialog/BankAccountEditDialogComponent.razor) blazor component.

re you points above:

1. Yep, I had already come to that deduction but I appreciate the heads up. So far the deployed package has done just fine. 

2. This was the area I was looking to raise a feature request / PR for. The issue is that blazor webasm doesn't have a command binding analogous to that found in the various XAML dialects. Instead getting MVVM to work in blazor requires a fair bit of liberal use of lambdas to hook the events to the corresponding VM command as in the OnClick handler for save and cancel buttons shown here:
``` razor
  <DialogButtons>
    <DialogButton OnClick="@(_ => this.vm.Cancel.ExecuteAsync(null))" Disabled="@(!this.vm.Cancel.CanExecute(null))" Content="Discard" IconCss="fa fa-lg fa-trash-o" />
    <DialogButton OnClick="@(_ => this.vm.Save.ExecuteAsync(null))" Disabled="@(!this.vm.Save.CanExecute(null))" Content="Save" IconCss="fa fa-lg fa-floppy-o" IsPrimary="true" />
  </DialogButtons>
```
by comparison, the same WPF XAML would be
``` xaml
    <StackPanel Grid.Row="7" Grid.Column="1" Grid.ColumnSpan="10" Orientation="Horizontal" HorizontalAlignment="Right">
      <Button Command="{Binding Cancel}" Content="Cancel" Margin="0,0,8,0" Padding="8,4,8,4" />
      <Button Command="{Binding Save}" Padding="8,4,8,4">
        <StackPanel Orientation="Horizontal">
          <iconPacks:PackIconFontAwesome Kind="SaveRegular"/>
          <TextBlock Padding="4,0,0,0" VerticalAlignment="Center">Save</TextBlock>
        </StackPanel>
      </Button>
    </StackPanel>
```

So as you can see the addition of another overload to make the nullable parameter argument entirely optional would remove the need to pass it in on the blazor side and clean the code up nicely. Something that is particularly important when trying to keep the amount of 'script' code mixed into the razor markup to a minimum.
